def B_readables():
    return """
BkPln_GEO                     
BkPln_RES_QIE                 
BkPln_Spare_1_Counter         
BkPln_Spare_2_Counter         
BkPln_Spare_3_Counter         
BkPln_WTE                     
Bottom_RESET_N                
Bottom_TRST_N                 
CLOCKCOUNTER           
FIRMVERSION_MAJOR      
FIRMVERSION_MINOR      
FIRMVERSION_SVN        
I2CBUSID               
ID1                    
ID2                    
Igloo_VDD_Enable       
JTAGSEL                
JTAG_Select_Board      
JTAG_Select_FPGA       
ONES                   
ONESZEROES             
RESQIECOUNTER          
SCRATCH         
SHT_ident       
SHT_rh_f        
SHT_temp_f      
SHT_user        
Thermometer     
Top_RESET_N     
Top_TRST_N      
WTECOUNTER      
ZEROES          
orbit_histo_bin1
orbit_histo_bin2 
orbit_histo_bin3 
orbit_histo_bin4 
orbit_histo_bin5 
orbit_histo_bin6 
orbit_histo_bin7 
orbit_histo_clear
orbit_histo_run  
""".split()


def B_writables():
    return """
Bottom_RESET_N  
Bottom_TRST_N   
I2CBUSID        
Igloo_VDD_Enable
JTAGSEL           
JTAG_Select_Board 
JTAG_Select_FPGA  
SCRATCH           
SHT_softreset      
SHT_user           
Thermometer        
Top_RESET_N        
Top_TRST_N        
orbit_histo_clear 
orbit_histo_run   
"""


def i_readables():
    return """
AddrToSERDES          
BX_forSpy             
CapIdErrLink1_count   
CapIdErrLink2_count   
CapIdErrLink3_count   
ChAlignStatus         
Clk_count             
CntrReg_CImode        
CntrReg_InputSpyRst   
CntrReg_WrEn_InputSpy 
CntrReg_bit25         
CntrReg_bit27         
CntrReg_bit28         
CntrReg_bit29         
CntrReg_bit30         
CntrReg_bit31         
CntrReg_type2_Rst     
CntrReg_type3_Rst     
CtrlToSERDES_i2c_go   
CtrlToSERDES_i2c_write
DataFromSERDES               
DataToSERDES                 
FPGA_MAJOR_VERSION           
FPGA_MINOR_VERSION           
FPGA_TopOrBottom             
FiberID1                     
FiberID2                     
LinkTestMode                 
LinkTestPattern              
OnesRegister                 
Spy32bits                    
Spy96bits                    
SpyAtFixedBX                 
StatFromSERDES_busy          
StatFromSERDES_i2c_counter   
StatusReg_BRIDGE_SPARE       
StatusReg_InputSpyFifoEmpty  
StatusReg_InputSpyFifoFull   
StatusReg_InputSpyWordNum    
StatusReg_PLL320MHzLock      
StatusReg_QieDLLNoLock       
StatusReg_zero               
UniqueID			  
WTE_count			  
ZerosRegister              
bc0_gen_disable		   
bc0_gen_error		   
bc0_gen_locked		   
bc0_gen_warning		   
bc0_status_count_a	   
bc0_status_count_b	   
bc0_status_max_a	   
bc0_status_max_b	   
bc0_status_min_a	   
bc0_status_min_b	   
bc0_status_missing_a	   
bc0_status_missing_b	   
bc0_status_shift_a	   
bc0_status_shift_b	   
fifo_data_1		   
fifo_data_2		   
fifo_data_3		   
inputSpy		   
scratch			   
""".split()


def i_writables():
    return """
AddrToSERDES            
BX_forSpy               
CntrReg_CImode          
CntrReg_InputSpyRst     
CntrReg_WrEn_InputSpy   
CntrReg_bit25           
CntrReg_bit27           
CntrReg_bit28           
CntrReg_bit29           
CntrReg_bit30           
CntrReg_bit31           
CntrReg_type2_Rst       
CntrReg_type3_Rst       
CtrlToSERDES_i2c_go     
CtrlToSERDES_i2c_write  
DataToSERDES            
FiberID1                
FiberID2                
LinkTestMode            
LinkTestPattern         
SpyAtFixedBX            
UniqueID                
bc0_gen_disable         
bc0_gen_error           
bc0_gen_locked          
bc0_gen_warning         
bc0_status_count_a      
bc0_status_count_b      
bc0_status_max_a        
bc0_status_max_b        
bc0_status_min_a      
bc0_status_min_b      
bc0_status_missing_a  
bc0_status_missing_b  
bc0_status_shift_a    
bc0_status_shift_b    
fifo_data_1           
fifo_data_2           
fifo_data_3           
scratch               
""".split()
